name: compressor
description: "App to compress files."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  file_picker: ^9.2.2
  super_drag_and_drop: ^0.8.24
  super_clipboard: ^0.8.24
  path_provider: ^2.1.5
  provider: ^6.1.2
  process_run: ^1.2.4

  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/ffmpeg/ffmpeg_win.exe
    - assets/ffmpeg/ffmpeg_mac
    - assets/ffmpeg/ffmpeg_lin